// <auto-generated />
using Codedash.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Codedash.Server.Migrations.ProblemDb
{
    [DbContext(typeof(ProblemDbContext))]
    [Migration("20220412173904_Initial database creation")]
    partial class Initialdatabasecreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("Codedash.Shared.Problem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Chunks")
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUserMade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Output")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Problem");

                    b.HasData(
                        new
                        {
                            Id = "fbfc9038-b902-40e8-b0b4-fe3b11beb1c4",
                            Chunks = "print(\"Hi\")\nprint(0-1\"Hello, World!\"113)0-1",
                            Difficulty = 0,
                            IsUserMade = false,
                            Output = "Hi\nHello, World!",
                            Title = "Sample 0"
                        },
                        new
                        {
                            Id = "366f6e22-efd0-4e12-98af-99145881ccf3",
                            Chunks = "for i in range(6):\n    print(0-1\"ay\"16, end='')\nprint('9')\n\nprint('ay' * 64 + '9')0-1",
                            Difficulty = 0,
                            IsUserMade = false,
                            Output = "ayayayayayay9\nayayayayayayayayayayayayayayayayayayayayayayayayayayayayayayayayayayayayayayayayayayayayayayayayayayayayayayayayayayayayayayayay9",
                            Title = "Sample 1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
