// <auto-generated />
using Codedash.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Codedash.Server.Migrations.TokenDb
{
    [DbContext(typeof(TokenDbContext))]
    partial class TokenDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("Codedash.Shared.Token", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenString")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsernameHash")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Token");

                    b.HasData(
                        new
                        {
                            Id = "ca531d09-e896-4b1e-b11e-3a073cd29383",
                            TokenString = "QQ`\\\\5#Pm<6%rVVtmZ$}k_1a`qONUuF4#]@<Y#S^wbvR]|(y%B{Y$ZDDF6PHez!gRU.H$R(/__FWXOgo>S}lG,Z2.fn,:?mfXi[\"M'qvL,.^3dm-kO1xj$>PCV3tiv>%>|'HBcq5{.`LeG|-2~v<s-[Ua)I~FN|E6s?@L~b,,{j8pnHO-W%d,6e#zTq0-hGZ||!W0T07bafwq[?4EwP.|xCQWJtd=|Aw6zDrg%ah$)6Xg\"X,rza[K%sHRc:QtGwkIdulGru}mGq+N\"|yq6L8l`CR#YgDhy){6V*T^Ub8To!RhIIiLpTD*5&BJ,)p)<Gn\\Co8Ffk,*h7@&eG{vH%}tl0>TIoLsN%t3YED[Uspp)7j6EPd<w_r?*5rvzQ'B!@(/vc6[]df$Q.f5-D&>%LdQ(ChQ}K>!g_AgR(!-~\\El\\[f*o$4URfviHVIBV>>OtYyeKD2rumra'+`H>fuz\"?R$q2Z5NNG?#o|Gz71ktLZU(UrMn{G:l}(yh0iYs7(+Q?T",
                            UsernameHash = "3a2bdfc8841a6b57e71e90983ccd34cd7c8950d2d59506c9df7565978d1891ab11c7c2fc8948d1109eb098e8d016e2d4999a404d0e15ae0ce5637b0482446c0e"
                        },
                        new
                        {
                            Id = "931ba3e9-91d3-4b8d-8f85-c2854024ca87",
                            TokenString = "|<Z!<$hNHZnZMF-G7!qt$e:9G47|(d&UEC.%='^y#iY%*xQU?5RBGH^igG${`'kgAPPki/bK#((V#wS,1xRSC[S]|SnU6ie,bVN'ufMK-FK^Ck@u`Q]=,QWR~HSjH/URLfDX8YIzA;3.p+{&ENfAHQxw30L]H3hSS})Bj8X%`^\"t7>+|5bJ%IPGQVyWR\"&Z]wce]|OB=*'Q%2hQI|X_jsCn3*<&+3JHMHBEMumA(vq\"X^ttSUY``9:]5>;/4wf%4)s9@&qi8dOs6iTbQ:}4qHhyeXv\\O>on>#FbW)Xv4;%3Yi-uokO(8fHh^jQc*,L\\G#OO6K*]LKp~mo(&2-jVhAA3Pi5If/zawo|m`AAGh>RxJ1KV3VyIq\"O1fE!Klo%m#O..|?K6dTT:zQqtK>+Fq~MOwP)Q20WZtOuO},t)c{-3VFLo053Xz8!7Ufp:T9kG^EciaW:9@`S5;ujZ~kKxi&'QB^Vls/:RY#2d4mKNPE,$(dorE^#rPDOKg+rB#=Co@",
                            UsernameHash = "4a2bdfc8841a6b57e71e90983ccd34cd7c8950d2d59506c9df7565978d1891ab11c7c2fc8948d1109eb098e8d016e2d4999a404d0e15ae0ce5637b0482446c0e"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
