// <auto-generated />
using System;
using Codedash.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Codedash.Server.Migrations
{
    [DbContext(typeof(AccountDbContext))]
    partial class AccountDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("Codedash.Shared.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AverageTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Solved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Submissions")
                        .HasColumnType("TEXT");

                    b.Property<int>("SubmissionsNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsernameHash")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Account");

                    b.HasData(
                        new
                        {
                            Id = "af0b3528-ff50-450c-a6d8-7a6c49a35878",
                            AverageTime = 0m,
                            DisplayName = "Generic PCI Device",
                            PasswordHash = "c2015c71296c09ac3279d2d27a35b0fd58bb39f5b184a160f52e39c495056494f2eae2c84bc90f24013580bf9e34c318c98c27a85d0b88e63f4ef4c695d6699b",
                            RegistrationDate = new DateTime(2022, 4, 12, 17, 38, 30, 125, DateTimeKind.Utc).AddTicks(8680),
                            Solved = 0,
                            Submissions = "",
                            SubmissionsNum = 0,
                            UsernameHash = "3a2bdfc8841a6b57e71e90983ccd34cd7c8950d2d59506c9df7565978d1891ab11c7c2fc8948d1109eb098e8d016e2d4999a404d0e15ae0ce5637b0482446c0e"
                        },
                        new
                        {
                            Id = "cd8ca16f-0247-429a-be14-b4c8e9cca43c",
                            AverageTime = 0m,
                            DisplayName = "Generic electron",
                            PasswordHash = "d2015c71296c09ac3279d2d27a35b0fd58bb39f5b184a160f52e39c495056494f2eae2c84bc90f24013580bf9e34c318c98c27a85d0b88e63f4ef4c695d6699b",
                            RegistrationDate = new DateTime(2022, 4, 12, 17, 38, 30, 125, DateTimeKind.Utc).AddTicks(8704),
                            Solved = 0,
                            Submissions = "",
                            SubmissionsNum = 0,
                            UsernameHash = "4a2bdfc8841a6b57e71e90983ccd34cd7c8950d2d59506c9df7565978d1891ab11c7c2fc8948d1109eb098e8d016e2d4999a404d0e15ae0ce5637b0482446c0e"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
